//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Controles.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Controles: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""pajarosycerdos"",
            ""id"": ""575f5acf-81e1-4904-bcf6-46779172511e"",
            ""actions"": [
                {
                    ""name"": ""Presionado"",
                    ""type"": ""Button"",
                    ""id"": ""6c6e9624-0c01-4ca3-8131-fb24b8e44212"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Posicion"",
                    ""type"": ""Button"",
                    ""id"": ""1a25cf8d-a8ab-4349-a1d8-f094c6d0b5fc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""izquierdo"",
                    ""type"": ""Button"",
                    ""id"": ""453b880f-a9d9-4145-8bdf-155bccb37e5b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""barra"",
                    ""type"": ""Button"",
                    ""id"": ""74a90415-fba8-42c6-96f6-1c36e0711b58"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""13efd59f-1343-400c-a601-5645f355cd9d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Presionado"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d405c33-fb3a-457d-8cee-cfc0568d61b7"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Posicion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb827117-9bf8-45db-9d8b-066a049e55f0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Posicion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad1ca292-21e1-4c6f-94bb-d2ae54f80a76"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""izquierdo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d064a0a-3bfe-4320-9ba8-e0f66198984c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""barra"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // pajarosycerdos
        m_pajarosycerdos = asset.FindActionMap("pajarosycerdos", throwIfNotFound: true);
        m_pajarosycerdos_Presionado = m_pajarosycerdos.FindAction("Presionado", throwIfNotFound: true);
        m_pajarosycerdos_Posicion = m_pajarosycerdos.FindAction("Posicion", throwIfNotFound: true);
        m_pajarosycerdos_izquierdo = m_pajarosycerdos.FindAction("izquierdo", throwIfNotFound: true);
        m_pajarosycerdos_barra = m_pajarosycerdos.FindAction("barra", throwIfNotFound: true);
    }

    ~@Controles()
    {
        UnityEngine.Debug.Assert(!m_pajarosycerdos.enabled, "This will cause a leak and performance issues, Controles.pajarosycerdos.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // pajarosycerdos
    private readonly InputActionMap m_pajarosycerdos;
    private List<IPajarosycerdosActions> m_PajarosycerdosActionsCallbackInterfaces = new List<IPajarosycerdosActions>();
    private readonly InputAction m_pajarosycerdos_Presionado;
    private readonly InputAction m_pajarosycerdos_Posicion;
    private readonly InputAction m_pajarosycerdos_izquierdo;
    private readonly InputAction m_pajarosycerdos_barra;
    /// <summary>
    /// Provides access to input actions defined in input action map "pajarosycerdos".
    /// </summary>
    public struct PajarosycerdosActions
    {
        private @Controles m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PajarosycerdosActions(@Controles wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "pajarosycerdos/Presionado".
        /// </summary>
        public InputAction @Presionado => m_Wrapper.m_pajarosycerdos_Presionado;
        /// <summary>
        /// Provides access to the underlying input action "pajarosycerdos/Posicion".
        /// </summary>
        public InputAction @Posicion => m_Wrapper.m_pajarosycerdos_Posicion;
        /// <summary>
        /// Provides access to the underlying input action "pajarosycerdos/izquierdo".
        /// </summary>
        public InputAction @izquierdo => m_Wrapper.m_pajarosycerdos_izquierdo;
        /// <summary>
        /// Provides access to the underlying input action "pajarosycerdos/barra".
        /// </summary>
        public InputAction @barra => m_Wrapper.m_pajarosycerdos_barra;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_pajarosycerdos; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PajarosycerdosActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PajarosycerdosActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PajarosycerdosActions" />
        public void AddCallbacks(IPajarosycerdosActions instance)
        {
            if (instance == null || m_Wrapper.m_PajarosycerdosActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PajarosycerdosActionsCallbackInterfaces.Add(instance);
            @Presionado.started += instance.OnPresionado;
            @Presionado.performed += instance.OnPresionado;
            @Presionado.canceled += instance.OnPresionado;
            @Posicion.started += instance.OnPosicion;
            @Posicion.performed += instance.OnPosicion;
            @Posicion.canceled += instance.OnPosicion;
            @izquierdo.started += instance.OnIzquierdo;
            @izquierdo.performed += instance.OnIzquierdo;
            @izquierdo.canceled += instance.OnIzquierdo;
            @barra.started += instance.OnBarra;
            @barra.performed += instance.OnBarra;
            @barra.canceled += instance.OnBarra;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PajarosycerdosActions" />
        private void UnregisterCallbacks(IPajarosycerdosActions instance)
        {
            @Presionado.started -= instance.OnPresionado;
            @Presionado.performed -= instance.OnPresionado;
            @Presionado.canceled -= instance.OnPresionado;
            @Posicion.started -= instance.OnPosicion;
            @Posicion.performed -= instance.OnPosicion;
            @Posicion.canceled -= instance.OnPosicion;
            @izquierdo.started -= instance.OnIzquierdo;
            @izquierdo.performed -= instance.OnIzquierdo;
            @izquierdo.canceled -= instance.OnIzquierdo;
            @barra.started -= instance.OnBarra;
            @barra.performed -= instance.OnBarra;
            @barra.canceled -= instance.OnBarra;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PajarosycerdosActions.UnregisterCallbacks(IPajarosycerdosActions)" />.
        /// </summary>
        /// <seealso cref="PajarosycerdosActions.UnregisterCallbacks(IPajarosycerdosActions)" />
        public void RemoveCallbacks(IPajarosycerdosActions instance)
        {
            if (m_Wrapper.m_PajarosycerdosActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PajarosycerdosActions.AddCallbacks(IPajarosycerdosActions)" />
        /// <seealso cref="PajarosycerdosActions.RemoveCallbacks(IPajarosycerdosActions)" />
        /// <seealso cref="PajarosycerdosActions.UnregisterCallbacks(IPajarosycerdosActions)" />
        public void SetCallbacks(IPajarosycerdosActions instance)
        {
            foreach (var item in m_Wrapper.m_PajarosycerdosActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PajarosycerdosActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PajarosycerdosActions" /> instance referencing this action map.
    /// </summary>
    public PajarosycerdosActions @pajarosycerdos => new PajarosycerdosActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "pajarosycerdos" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PajarosycerdosActions.AddCallbacks(IPajarosycerdosActions)" />
    /// <seealso cref="PajarosycerdosActions.RemoveCallbacks(IPajarosycerdosActions)" />
    public interface IPajarosycerdosActions
    {
        /// <summary>
        /// Method invoked when associated input action "Presionado" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPresionado(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Posicion" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosicion(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "izquierdo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIzquierdo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "barra" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBarra(InputAction.CallbackContext context);
    }
}
